version: '3.8'
services:
  app:
    image: aapurva/getting-started:v1.0.0-alpine
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - todo-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - todo-app
  
volumes:
  todo-mysql-data:
networks:
  todo-app:


