apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItaG9zdDo1MDAwIjp7InVzZXJuYW1lIjoiZG9ja191c2VyIiwicGFzc3dvcmQiOiJkb2NrX3Bhc3N3b3JkIiwiZW1haWwiOiJkb2NrX3VzZXJAZG9ja2VyLWhvc3QiLCJhdXRoIjoiWkc5amExOTFjMlZ5T21SdlkydGZjR0Z6YzNkdmNtUT0ifX19
kind: Secret
metadata:
  name: private-reg-cred
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: todo-app-deployment
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      imagePullSecrets: 
      - name: private-reg-cred
      containers:
        - name: todo-app
          image: aapurva/getting-started:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service 
metadata: 
  name: todo-app-svc
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - port: 3000
      targetPort: 3000