name: Build and Analyze Getting started app

on:
 
  push:
    branches:
      - main
  
  workflow_dispatch:
    

jobs:
  
  build_and_analyze:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

          

